-- ========================================================
-- Script DDL: SISTEMA_VENDAS_DDL_V1.0
-- Ambiente: Oracle Database / Oracle APEX
-- Objetivo: Criação das 6 tabelas fundamentais do Sistema
--           de Vendas e Análise Comercial
-- ========================================================

-- ========================================================
-- 1. TB_CLIENTE (Tabela de Clientes)
--    Tabela sem chaves estrangeiras - criada primeiro
-- ========================================================
CREATE TABLE tb_cliente (
    id_cliente      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(150) NOT NULL,
    email           VARCHAR2(150) NOT NULL,
    cpf             VARCHAR2(11),
    ativo           CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT un_cliente_email UNIQUE (email),
    CONSTRAINT un_cliente_cpf UNIQUE (cpf),
    CONSTRAINT chk_cliente_ativo CHECK (ativo IN ('S', 'N'))
);

-- ========================================================
-- 2. TB_VENDEDOR (Tabela de Vendedores)
--    Tabela sem chaves estrangeiras - criada primeiro
-- ========================================================
CREATE TABLE tb_vendedor (
    id_vendedor     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(150) NOT NULL,
    email           VARCHAR2(150) NOT NULL,
    ativo           CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_vendedor PRIMARY KEY (id_vendedor),
    CONSTRAINT un_vendedor_email UNIQUE (email),
    CONSTRAINT chk_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);

-- ========================================================
-- 3. TB_CATEGORIA (Tabela de Categorias)
--    Tabela sem chaves estrangeiras - criada primeiro
-- ========================================================
CREATE TABLE tb_categoria (
    id_categoria    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome            VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria)
);

-- ========================================================
-- 4. TB_PRODUTO (Tabela de Produtos)
--    Possui chave estrangeira para tb_categoria
-- ========================================================
CREATE TABLE tb_produto (
    id_produto      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria    NUMBER NOT NULL,
    sku             VARCHAR2(50) NOT NULL,
    nome            VARCHAR2(150) NOT NULL,
    preco_unit      NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_produto PRIMARY KEY (id_produto),
    CONSTRAINT fk_produto_categoria FOREIGN KEY (id_categoria)
        REFERENCES tb_categoria (id_categoria),
    CONSTRAINT un_produto_sku UNIQUE (sku),
    CONSTRAINT chk_produto_preco_unit CHECK (preco_unit > 0)
);

-- ========================================================
-- 5. TB_VENDA (Tabela de Cabeçalho de Vendas)
--    Possui chaves estrangeiras para tb_cliente e tb_vendedor
-- ========================================================
CREATE TABLE tb_venda (
    id_venda        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente      NUMBER NOT NULL,
    id_vendedor     NUMBER NOT NULL,
    dt_venda        DATE DEFAULT SYSDATE NOT NULL,
    valor_liquido   NUMBER(10, 2),
    canal           VARCHAR2(10) NOT NULL,
    status          VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_venda PRIMARY KEY (id_venda),
    CONSTRAINT fk_venda_cliente FOREIGN KEY (id_cliente)
        REFERENCES tb_cliente (id_cliente),
    CONSTRAINT fk_venda_vendedor FOREIGN KEY (id_vendedor)
        REFERENCES tb_vendedor (id_vendedor),
    CONSTRAINT chk_venda_canal CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    CONSTRAINT chk_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA'))
);

-- ========================================================
-- 6. TB_VENDA_ITEM (Tabela de Itens da Venda)
--    Possui chaves estrangeiras para tb_venda (ON DELETE CASCADE)
--    e tb_produto
-- ========================================================
CREATE TABLE tb_venda_item (
    id_venda_item       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda            NUMBER NOT NULL,
    id_produto          NUMBER NOT NULL,
    quantidade          NUMBER NOT NULL,
    valor_unit          NUMBER(10, 2) NOT NULL,
    percentual_desconto NUMBER(5, 2) DEFAULT 0 NOT NULL,
    valor_total         NUMBER(10, 2),
    CONSTRAINT pk_venda_item PRIMARY KEY (id_venda_item),
    CONSTRAINT fk_venda_item_venda FOREIGN KEY (id_venda)
        REFERENCES tb_venda (id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_venda_item_produto FOREIGN KEY (id_produto)
        REFERENCES tb_produto (id_produto),
    CONSTRAINT chk_venda_item_qtd CHECK (quantidade > 0),
    CONSTRAINT chk_venda_item_desc CHECK (percentual_desconto >= 0 AND percentual_desconto <= 50)
);

-- ========================================================
-- FIM DO SCRIPT
-- ========================================================
